services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: "host"
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # Persistent data storage
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default admin password (change as needed)
    volumes:
      - grafana_data:/var/lib/grafana  # Persistent storage for Grafana data
      - /etc/grafana/provisioning:/etc/grafana/provisioning  # Mount provisioning files
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus  # Ensures Prometheus starts before Grafana

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
