#!/bin/bash

elastic_username="elastic"
elastic_password2="elastic"
ip_address="192.168.2.72"

# Function to get Kibana dashboard URL
get_dashboard_url() {
  local kibana_url="http://$ip_address:5601"
  local dashboard_title="$1"
  
  # Encode the dashboard title for URL
  local encoded_title=$(echo "$dashboard_title" | sed 's/ /%20/g' | sed 's/:/%3A/g' | sed 's/(/%28/g' | sed 's/)/%29/g')

  # Perform the API request to find the dashboard
  local response=$(curl -s -u "$elastic_username:$elastic_password2" -X GET "$kibana_url/api/saved_objects/_find?type=dashboard&search_fields=title&search=$encoded_title" -H 'kbn-xsrf: true')

  # Extract the dashboard ID from the response
  local dashboard_id=$(echo "$response" | jq -r '.saved_objects[] | select(.attributes.title=="'"$dashboard_title"'") | .id')

  # Check if the dashboard ID is found
  if [ -z "$dashboard_id" ]; then
    echo "Dashboard not found"
  else
    # Construct the dashboard URL
    local dashboard_url="$kibana_url/app/kibana#/dashboard/$dashboard_id"
    echo "$dashboard_url"
  fi
}



dashboard_url=$(get_dashboard_url "ElastiFlow (flow): Overview")

# Use the dashboard_url variable
printf "----------------------------------------------\n"
printf "\e[5;37m\n\nGo to $dashboard_url ($elastic_username / $elastic_password2)\n\n\e[0m"
